/*
 * Copyright (C) 2024 Willian Junior <willianjunior.c.f@gmail.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package view;

import banco.UsuarioDAO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Usuario;
import view.CRUD.Read;

/**
 * @author Willian Junior <willianjunior.c.f@gmail.com>
 * @brief JFrame Cadastrar
 */

public class Cadastrar extends javax.swing.JFrame {

    // Construtor
    public Cadastrar() {
        // Inicialização dos componentes
        initComponents();
        // Responsavel por colocar a janela no meio da tela
        this.setLocationRelativeTo(null);
        // Responsavel por colocar o titulo na janela
        this.setTitle("Cadastrar Usuario");
        // Responsavel por mudar o icone da janela
        ImageIcon icon = new ImageIcon("src/main/resources/image/icon.png");
        this.setIconImage(icon.getImage());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jButton_Voltar = new javax.swing.JButton();
        jButton_Cadastrar = new javax.swing.JButton();
        jPasswordField_CPF = new javax.swing.JPasswordField();
        jTextField_Nome = new javax.swing.JTextField();
        jPasswordField_Senha = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 246, 246));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fundo-Cadastro.png"))); // NOI18N

        jTextField_Email.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_Email.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_EmailKeyPressed(evt);
            }
        });

        jButton_Voltar.setBackground(new java.awt.Color(249, 246, 246));
        jButton_Voltar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Voltar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Setinha de voltar.png"))); // NOI18N
        jButton_Voltar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_Voltar.setBorderPainted(false);
        jButton_Voltar.setFocusPainted(false);
        jButton_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VoltarActionPerformed(evt);
            }
        });

        jButton_Cadastrar.setBackground(new java.awt.Color(24, 100, 204));
        jButton_Cadastrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_Cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cadastrar.setText("Cadastrar");
        jButton_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CadastrarActionPerformed(evt);
            }
        });

        jPasswordField_CPF.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField_CPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPasswordField_CPF.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField_CPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_CPFKeyPressed(evt);
            }
        });

        jTextField_Nome.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField_Nome.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_NomeKeyPressed(evt);
            }
        });

        jPasswordField_Senha.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField_Senha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPasswordField_Senha.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField_Senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_SenhaKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cadastro");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Senha");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("CPF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jPasswordField_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jPasswordField_Senha)))
                            .addComponent(jButton_Cadastrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(60, 60, 60)))
                        .addGap(0, 65, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_Email, jTextField_Nome});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPasswordField_CPF, jPasswordField_Senha});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(24, 24, 24))
                                    .addComponent(jLabel3)))
                            .addComponent(jButton_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPasswordField_CPF, jPasswordField_Senha, jTextField_Email, jTextField_Nome});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Metod para validar o cadastro
    private void cadastrarUsuario(){
        // Pode passar apenas nome e sobrenome
        if(jTextField_Nome.getText().matches("^[a-zA-Zà-úÀ-Úâ-ûÂ-ÛçÇ]+(\\s[a-zA-Zà-úÀ-Úâ-ûÂ-ÛçÇ]+)+$")){ 
            // Pode passar apenas com gmail, hotmail e outlook
            if(jTextField_Email.getText().matches("^.+@(gmail\\.com|hotmail\\.com|outlook\\.(com|com\\.br))$")){
                // Chamo o metodo para validar o CPF
                if(Usuario.ValidarCPF(String.valueOf(jPasswordField_CPF.getPassword()))){
                    // Tamnho minimo de 5 e maximo de 50 para a senha
                    if(String.valueOf(jPasswordField_Senha.getPassword()).matches(".{5,50}")){
                        // Caso passe por todas as validações eu instancio um objeto com as informações
                        Usuario usuario = new Usuario(
                           jTextField_Nome.getText(),
                           String.valueOf(jPasswordField_CPF.getPassword()),
                           jTextField_Email.getText(),
                           String.valueOf(jPasswordField_Senha.getPassword())
                        );
                        
                        // Instancio o objeto Usuario do banco de dados
                        UsuarioDAO usuarioDAO = new UsuarioDAO();
                        // Verificação se inserir no banco
                        if (usuarioDAO.inserirUsuario(usuario)) {
                            // Se passar mostro uma mensagem na tela
                            JOptionPane.showMessageDialog(this, "Usuario cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                            // Instancio o objeto da tela
                            Read menu = new Read();
                            // this.dispose vai desligar a janela atual
                            this.dispose();
                            // E deixo visivel a tela principal
                            menu.setVisible(true);
                            // A seguir os erros
                        } else {
                            JOptionPane.showMessageDialog(this, "Erro ao cadastrar o usuario.", "Erro", JOptionPane.ERROR_MESSAGE);
                        }

                     } else JOptionPane.showMessageDialog(this, "Senha invalida", "Erro", JOptionPane.ERROR_MESSAGE);
                } else JOptionPane.showMessageDialog(this, "CPF invalido", "Erro", JOptionPane.ERROR_MESSAGE);
            } else JOptionPane.showMessageDialog(this, "Email invalido", "Erro", JOptionPane.ERROR_MESSAGE);
        } else JOptionPane.showMessageDialog(this, "Nome invalido", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    // Metodo para o botão Cadastrar
    private void jButton_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CadastrarActionPerformed
        // Apenas chama o metodo para validar
        cadastrarUsuario();
    }//GEN-LAST:event_jButton_CadastrarActionPerformed

    // Metodo para o botão voltar
    private void jButton_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VoltarActionPerformed
        // Da mesma forma que eu liguei o menu no primeiro metodo, funciona da mesma forma
        Login loginTela = new Login();
        this.dispose();
        loginTela.setVisible(true);
    }//GEN-LAST:event_jButton_VoltarActionPerformed

    // Metodos para capturar o ENTER em qualquer campo e inicializar o metodo de validar
    private void jTextField_NomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NomeKeyPressed
        if(evt.getKeyCode() == 10) {
            cadastrarUsuario();
        }
    }//GEN-LAST:event_jTextField_NomeKeyPressed

    private void jTextField_EmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_EmailKeyPressed
        if(evt.getKeyCode() == 10) {
            cadastrarUsuario();
        }
    }//GEN-LAST:event_jTextField_EmailKeyPressed

    private void jPasswordField_CPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_CPFKeyPressed
        if(evt.getKeyCode() == 10) {
            cadastrarUsuario();
        }
    }//GEN-LAST:event_jPasswordField_CPFKeyPressed

    private void jPasswordField_SenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_SenhaKeyPressed
        if(evt.getKeyCode() == 10) {
            cadastrarUsuario();
        }
    }//GEN-LAST:event_jPasswordField_SenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cadastrar;
    private javax.swing.JButton jButton_Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_CPF;
    private javax.swing.JPasswordField jPasswordField_Senha;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Nome;
    // End of variables declaration//GEN-END:variables
}
